name: Compile LaTeX and Deploy to Pages

on:
  push:
    branches:
      - main  # 当你向 main 分支推送代码时触发

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install TeXLive
        uses: dante-ev/latex-action@v1
        with:
          root_file: main.tex # 将这里的 main.tex 替换为你的主论文文件名
          compiler: xelatex   # 根据你的需求选择编译器，如 pdflatex, xelatex, lualatex

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: . # 将编译好的文件部署到 gh-pages 分支的根目录
          keep_files: false # 每次部署时清空目标目录
          force_orphan: true # 强制创建一个独立的 orphan 分支，保证干净